// Versioned check registry — the Margin/audit-engine pattern: every finding
// records the check version that produced it; bump a version whenever logic
// changes. Severity: FAIL blocks the preflight; WARN passes with caution;
// INFO is context.

export const ENGINE_VERSION = '0.4.0'

export const CHECKS = [
  {
    id: 'code-name-missing',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Code references a device name that is not in the active configuration',
    why: 'This is FTC\'s single most common failure: "Unable to find a hardware device with the name…" thrown at runtime — worst case, on the field. The name must match in exactly two hand-typed places and nothing checks it until now.',
  },
  {
    id: 'config-name-unused',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Configured device never referenced by any scanned OpMode',
    why: 'Often a renamed device whose old entry survived, or a mechanism the code silently lost.',
  },
  {
    id: 'duplicate-name',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Two configured devices share a name',
    why: 'hardwareMap lookups become ambiguous; behavior depends on config order.',
  },
  {
    id: 'port-collision',
    version: '0.2.0',
    severity: 'FAIL',
    name: 'Two devices declared on the same port of the same hub (within one port space)',
    why: 'Motor/servo/digital/analog ports and I2C bus positions are exclusive; a collision means at least one declaration is wrong.',
  },
  {
    id: 'hub-address-conflict',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Duplicate hub module addresses (including the dual default-address-2 trap)',
    why: 'Expansion Hubs ship at address 2; two unmodified hubs conflict, and official docs warn a config "will no longer find" a hub after an address change.',
  },
  {
    id: 'name-hygiene',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Device names that differ only by case or whitespace',
    why: 'Names this similar are typo bait across the config/code boundary.',
  },
  {
    id: 'drift',
    version: '0.2.0',
    severity: 'WARN',
    name: 'Configuration changed since the last recorded PASS snapshot',
    why: 'Surfaces silent rewires and hub swaps — with targeted fix guidance instead of the SCAN that wipes the whole config.',
  },
  {
    id: 'unparsed',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Input the parser could not confidently read',
    why: 'PHYSYNC never drops what it cannot parse — ambiguity is surfaced, not buried (the audit-engine rule).',
  },
  {
    id: 'port-range',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Port outside the hub\'s physical range',
    why: 'REV hubs have motor 0-3, servo 0-5, digital 0-7, analog 0-3, I2C bus 0-3. Impossible ports come from hand-edited XML — a workflow PHYSYNC itself recommends during swap recovery.',
  },
  {
    id: 'unknown-device-type',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Device type not recognized — excluded from port-collision checking',
    why: 'Unknown tags (custom @DeviceProperties drivers) cannot be assigned a port space; saying so beats silently exempting them (QA: a SPARKmini/servo double-booking sailed through unannounced).',
  },
  {
    id: 'i2c-address-conflict',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Two identical I2C sensors on one bus',
    why: 'Same-model sensors answer at the same fixed I2C address (e.g. 0x52) — they cannot coexist on one bus; reads return garbage. The classic splitter trap.',
  },
  {
    id: 'digital-pair-overlap',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Digital devices on both channels of one physical connector pair',
    why: 'REV digital connectors carry channel pairs (0-1, 2-3, 4-5, 6-7); a REV Touch Sensor occupies its whole pair, so a second device on the partner channel usually cannot be plugged in.',
  },
  {
    id: 'parent-address-mismatch',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Portal parentModuleAddress points at no declared hub',
    why: 'The aftermath of re-addressing a hub in the REV Hardware Client without updating the config — official docs warn the config "will no longer find" that hub.',
  },
  {
    id: 'blocks-name-unknown',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Blocks OpMode references an identifier that matches no configured device',
    why: 'Blocks hardware identifiers regenerate from the active config, so a stale one usually means the config changed after the OpMode was written. WARN not FAIL: the identifier convention (name + As + Type) is verified against real team .blk files (corpus, 2026-09-07) but not against SDK generation source — confirm surprising cases in the Blocks editor.',
  },
  {
    id: 'servo-position-out-of-range',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Servo commanded to a position outside 0.0–1.0',
    why: 'The SDK clamps silently, so the servo stops somewhere the programmer did not intend while the code reads as if it worked. PHYSYNC cannot know your mechanism\'s physical safe range, but a value outside the legal range is wrong on its face.',
  },
  {
    id: 'servo-scale-range-invalid',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'scaleRange() called with arguments the SDK rejects',
    why: 'Requires 0.0 ≤ min < max ≤ 1.0; anything else throws and the OpMode dies at init.',
  },
  {
    id: 'servo-class-mismatch',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Config device type and the code\'s servo class contradict each other',
    why: 'A continuous-rotation servo has no positions and a positional servo has no power. Either mismatch throws at runtime — a config/code disagreement of exactly the kind PHYSYNC exists to catch.',
  },
  {
    id: 'sensor-not-responding',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'I2C sensor did not answer after three reads',
    why: 'Unlike a motor under load, an I2C sensor has no benign reason to throw on every read — it is not on the bus. Retried three times on the robot so a transient glitch cannot raise a false alarm.',
  },
  {
    id: 'sensor-reads-zero',
    version: '0.1.0',
    severity: 'WARN',
    name: 'I2C sensor answered but read all zeros',
    why: 'A live sensor essentially never reads zero on every channel at once, but the inference is weaker than an outright bus error — so it warns and tells the student how to confirm by hand.',
  },
  {
    id: 'sensor-response-lost',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'A sensor that answered on the verified baseline does not now',
    why: 'Unambiguous change from a known-good state — cable, port, or configuration.',
  },
  {
    id: 'sensor-liveness-unavailable',
    version: '0.1.0',
    severity: 'INFO',
    name: 'Liveness cannot be determined for a digital or analog pin',
    why: 'A hub pin reads a value whether or not anything is attached, and a floating input looks legitimate. Saying so out loud is the difference between an honest tool and one that quietly implies more coverage than it has.',
  },
  {
    id: 'stimulus-nothing-verified',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'The stimulus pass measured nothing',
    why: 'Without a coverage floor, an empty or fully interrupted report renders a green PASS and asserts that every device responded — a claim about evidence that does not exist. Nothing measured is nothing verified.',
  },
  {
    id: 'stimulus-report-inconsistent',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'A stimulus result contradicts its own encoder evidence',
    why: 'A report claiming moved-positive with a negative delta was hand-edited, truncated, or written by a different version. Trusting either half would be a guess.',
  },
  {
    id: 'stimulus-not-compared',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'A baseline device was interrupted and therefore never checked',
    why: 'Silence here would let a reversal hide behind a mid-pulse stop — the run looks green while the device was never measured.',
  },
  {
    id: 'sensor-nothing-verified',
    version: '0.2.0',
    severity: 'INFO',
    name: 'The preflight read no sensor whose liveness is determinable',
    why: 'The danger was the green "ALL ANSWERING" banner over an empty set, so the BANNER is what changed. A robot with only touch sensors and no I2C devices is completely legitimate — failing it would be exactly the false alarm this project refuses to ship.',
  },
  {
    id: 'stimulus-no-response',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Motor was commanded but the encoder did not move',
    why: 'Ambiguous by nature — unplugged motor, unplugged encoder cable, wrong port, or a mechanism under load a weak pulse cannot shift. WARN not FAIL: a false red light in a pit destroys the trust the whole product runs on.',
  },
  {
    id: 'stimulus-response-lost',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'A device that responded on the verified baseline does not respond now',
    why: 'Unambiguous change since the robot was known good — the exact wire-disconnected / wrong-port failure a preflight exists to catch.',
  },
  {
    id: 'stimulus-direction-changed',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Motor direction reversed since the verified baseline',
    why: 'The motor was rewired, replaced, or its setDirection edited. Autonomous paths and encoder math that assume the old direction are now wrong.',
  },
  {
    id: 'stimulus-servo-unconfirmed',
    version: '0.1.0',
    severity: 'WARN',
    name: 'Servo nudge was not confirmed by a human',
    why: 'Servos have no positional feedback, so confirmation is a human observation — reported as such, never inferred.',
  },
  {
    id: 'stimulus-coverage',
    version: '0.1.0',
    severity: 'INFO',
    name: 'Device skipped, interrupted, or absent from the baseline',
    why: 'What was NOT verified is part of an honest report — silent coverage gaps read as PASS.',
  },
  {
    id: 'approval-missing',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'No readable approval on record',
    why: 'The gate\'s entire claim is "this is still the robot you approved." With no approval — or a corrupted one — that claim cannot be evaluated, and a gate that passes anyway is a green light over nothing. Fail closed.',
  },
  {
    id: 'approval-config-drift',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Active configuration differs from the approved one',
    why: 'The config changed, or a different config was activated, since a human verified and approved this robot. That is the exact drift the approval exists to catch.',
  },
  {
    id: 'approval-hub-drift',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Hub census or firmware differs from the approved robot',
    why: 'A hub missing, added, re-addressed, or re-flashed since approval is unambiguous physical change from a known-good state.',
  },
  {
    id: 'approval-bad-signature',
    version: '0.1.0',
    severity: 'FAIL',
    name: 'Approval signature does not verify with this laptop\'s gate key',
    why: 'The manifest was not produced by this laptop\'s `physync approve` (or the key changed). Provenance only — the HMAC proves which laptop signed it, not that the robot is safe, and PHYSYNC never claims more than that.',
  },
  {
    id: 'approval-signature-unverified',
    version: '0.1.0',
    severity: 'WARN',
    name: 'No gate key on this laptop — the approval\'s provenance was not checked',
    why: 'Digest self-consistency still holds, but with no key nothing proves WHICH laptop wrote this manifest — and the fleet demonstrated a tampered manifest with honestly recomputed digests passing green on a keyless machine. Saying "unverified" out loud is the difference between a checked green light and an assumed one.',
  },
  {
    id: 'approval-hubs-not-covered',
    version: '0.1.0',
    severity: 'INFO',
    name: 'Approval was recorded without a robot report — hub layer not covered',
    why: 'An approval made from config+code alone gates the declaration layer only. Saying which layer is NOT covered is what keeps the green light honest.',
  },
  {
    id: 'dynamic-name',
    version: '0.1.0',
    severity: 'INFO',
    name: 'Device name built at runtime — cannot be verified statically',
    why: 'Loops like get(Type.class, "module" + i + "_motor") are real (swerve, odometry); PHYSYNC reports what it cannot check instead of guessing.',
  },
]

export const checkMeta = (id) => CHECKS.find((c) => c.id === id)
